services:
  devcontainer:
    container_name: rawb-devcontainer
    image: rawb-devcontainer:local
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "${RAWB_SSH_PORT:-2255}:22"
    volumes:
      - type: bind
        source: /docker/pelican/mounts/dev-main/plugins/MagicSpells
        target: /home/pelican/dev-main
      - type: bind
        source: /docker/pelican/mounts/old-dev/plugins/MagicSpells
        target: /home/pelican/old-dev
      - type: volume
        source: ssh-host-keys
        target: /etc/ssh/host-keys
      - type: volume
        source: pelican-persistent
        target: /home/pelican/persistent
    working_dir: /home/pelican/old-dev

volumes:
  ssh-host-keys:
  pelican-persistent:
